### ISSUE TITLE
Unbind with routing key not working in Android

### ISSUE THREAD

**Issue by GianfrancoFois** [kegaretail/react-native-rabbitmq#13]
When you try to unbind a queue with a routing key, it doesn't use the passed parameter, only unbinds the last binded routing key.

When you do:

```
queue.bind(exchange, "my.routing.key");
queue.bind(exchange, "other.routing.key");
```

And later:

`queue.unbind(exchange, "my.routing.key");`

It unbinds "other.routing.key"

**Comment by timhonders** [comment]
Tnx for fixing it.
