### ISSUE TITLE
hi, i very interest and thank you

### ISSUE THREAD

**Issue by dotnetnat** [kegaretail/react-native-rabbitmq#2]
how to publish send message?

**Comment by timhonders** [comment]
Hi,

I was on vacation so sorry for late reaction.

https://github.com/kegaretail/react-native-rabbitmq#usage

u need to send the message via the exchange

let message = 'test';
let routing_key = '';
let properties = {
	expiration: 10000
}
exchange.publish(data, routing_key, properties)

**Comment by kreactnative** [comment]
thank you very much.
