### ISSUE TITLE
Exchange message receive

### ISSUE THREAD

**Issue by ShortByte** [kegaretail/react-native-rabbitmq#5]
I wanted to know how I received messages about certain routes via the "Exchange". 
Anybody here have any idea how I can do it?

**Comment by timhonders** [comment]
let message = 'test';
let routing_key = '';
let properties = {
	expiration: 10000
}
exchange.publish(data, routing_key, properties)


Do u mean via a routing_key?

**Comment by ShortByte** [comment]
I meant that I can receive the data via "routing keys" from other applications with the application.

**Comment by timhonders** [comment]
Yes, you should be able to do that.

If u bind a queue with a second parameter to a exchange like:
queue.bind(exchange, 'queue_name');

If u send data from a other app. to this exchange with the routing_key

U should get the data in:

queue.on('message', (data) => {

});
