### ISSUE TITLE
undefined is not an object (evaluating 'this.rabbitmqconnection.initialize')

### ISSUE THREAD

**Issue by vinaydanaraddi** [kegaretail/react-native-rabbitmq#7]
Hi, I am facing this issue while trying out the example in react native

TypeError: undefined is not an object (evaluating 'this.rabbitmqconnection.initialize')

This error is located at:
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

**Comment by itsmrTech** [comment]
+1

**Comment by bakead17** [comment]
I am also having this issue, has anyone resolved?

**Comment by bakead17** [comment]
I resolved this by making a new react-native app without using expo.

**Comment by qaniqani** [comment]
I m solved!
The interface in the library downloaded for ios is incorrect.
No equivalent function to provide the connection.
Try compiling the library open.

**Comment by hposaday** [comment]
> No equivalent function to provide the connection.

hello, i have the same issue :( can you please explain me how you solved it? i don't understand your solution as you describe it

**Comment by qaniqani** [comment]
![Screen Shot 2019-03-22 at 03 41 28](https://user-images.githubusercontent.com/19714568/54795343-7f680c80-4c54-11e9-9612-506f552206cb.png)

No provision of the connection method in the image.
Open the RMClient library and compare it.
You must have edited the reactor-native-RabbitMQ plugins.
You must edit the self.connection method.

**Comment by marketmix-matteoquintero** [comment]
Hello @qaniqani 
Hi, I'm new to ios, you can explain to me what I have to do with the method.
thankssssss

**Comment by timhonders** [comment]
I wil look at this soon

**Comment by cihanbs93** [comment]
I am getting this error on Android using Expo. Can it be about Expo?

**Comment by timhonders** [comment]
I don't think so.

Did the react-native link run correctly?

**Comment by cihanbs93** [comment]
Expo doesn't support linking libraries. That's why **react-native link** doesn't work.

**Comment by timhonders** [comment]
Should be fixed now, this plugin is now compatible with the 0.11.0 version of the ios library
