### ISSUE TITLE
Messages are missing sometimes 

### ISSUE THREAD

**Issue by pradhul** [kegaretail/react-native-rabbitmq#8]
I am pushing messages periodically from server and some of the messages seem missing and in android log I get the following error for the missed messages

Calling JS function after bridge has been destroyed:

**Comment by timhonders** [comment]
We implemented basic Ack, so if u can acknowledge in JS.

If the JS bridge is destroyed the messages should stay queued

**Comment by qaniqani** [comment]
![resim](https://user-images.githubusercontent.com/19714568/53901434-052e6a00-4050-11e9-9804-7884c528dd10.png)

**Comment by qaniqani** [comment]
![resim](https://user-images.githubusercontent.com/19714568/53901479-1b3c2a80-4050-11e9-8371-307d533b9d7e.png)

**Comment by qaniqani** [comment]
android - ios routing key diff
if(Platform.OS === 'android'){
                    if(data.queue_name===store.q && data.routing_key===store.q)
                        EventRegister.emit('me', '')
                }

                if(Platform.OS === 'ios'){
                    if(data.queue_name===store.q && data.routingKey===store.q)
                        EventRegister.emit('me', '')
                }

**Comment by timhonders** [comment]
Added routing_key to ios, still keeping routingKey for backward compatability
